//
//  PCBrush.swift
//  MusePro
//
//  Created by Omer Karisman on 22.01.24.
//

import Foundation
import SwiftUI

class PCBrush: NSObject, NSSecureCoding {
    static var supportsSecureCoding: Bool = true
    var archiveURL: URL?
    var previewPath: String = ""
    // Define properties that you expect in SilicaBrush
    // For example:
    var attackTilt: Bool = false
    var attackTiltAngle: Float = 0.4
    var authorName: String = ""
    var bleedTiltAngle: Float = 0.4
    var blendGammaCorrect: Bool = false
    var blendMode: Int = 0
    var brightnessTiltAngle: Float = 0.4
    var bundledGrainPath: String = ""
    var bundledHeightPath: String = ""
    var bundledMetallicPath: String = ""
    var bundledRoughnessPath: String = ""
    var bundledShapePath: String = ""
    var burntEdgesAmount: Float = 0.0
    var burntEdgesBlendMode: Int = 1
    var color: Color = Color(uiColor: UIColor())
    var creationDate: NSDate = NSDate()
    var darknessJitterTilt: Bool = false
    var darknessJitterTiltAngle: Float = 0.4
    var dualBlendMode: Int = 0
    var dynamicsBlur: Float = 0.0
    var dynamicsBlurJitter: Float = 0.0
    var dynamicsFalloff: Float = 0.0
    var dynamicsGlazedFlow: Float = 1
    var dynamicsJitterDarkness: Float = 0.0
    var dynamicsJitterHue: Float = 0.0
    var dynamicsJitterLightness: Float = 0.0
    var dynamicsJitterOpacity: Float = 0.0
    var dynamicsJitterSaturation: Float = 0.0
    var dynamicsJitterSize: Float = 0.0
    var dynamicsJitterStrokeDarkness: Float = 0.0
    var dynamicsJitterStrokeHue: Float = 0.0
    var dynamicsJitterStrokeLightness: Float = 0.0
    var dynamicsJitterStrokeSaturation: Float = 0.0
    var dynamicsLoad: Float = 0.0
    var dynamicsMix: Float = 0.0
    var dynamicsMixSoftening: Float = 0.0
    var dynamicsPressureBleed: Float = 0.0
//    var dynamicsPressureBleedCurve: String = ""
    var dynamicsPressureBleedSpeed: Float = 0.59
    var dynamicsPressureBrightness: Float = 0.0
//    var dynamicsPressureBrightnessCurve: String = ""
    var dynamicsPressureHue: Float = 0.0
//    var dynamicsPressureHueCurve: String = ""
    var dynamicsPressureMix: Float = 0.0
    var dynamicsPressureOpacity: Float = 0.68
//    var dynamicsPressureOpacityCurve: String = ""
    var dynamicsPressureOpacitySpeed: Float = 0.59
    var dynamicsPressureOpacityTransfer: Float = 0.0
    var dynamicsPressureResponse: Float = 0.0
    var dynamicsPressureSaturation: Float = 0.0
//    var dynamicsPressureSaturationCurve: String = ""
    var dynamicsPressureSecondaryColor: Float = 0.0
//    var dynamicsPressureSecondaryColorCurve: String = ""
    var dynamicsPressureShapeRoundness: Float = 1
//    var dynamicsPressureShapeRoundnessCurve: String = ""
    var dynamicsPressureShapeRoundnessMinimum: Float = 1
    var dynamicsPressureSize: Float = 0.0
//    var dynamicsPressureSizeCurve: String = ""
    var dynamicsPressureSizeSpeed: Float = 0.59
    var dynamicsPressureSmoothing: Float = 0.0
    var dynamicsPressureTransferModulationCurve: String = ""
    var dynamicsSmudgeAccumulation: Float = 0.60
    var dynamicsSpeedOpacity: Float = 0.0
    var dynamicsSpeedSize: Float = 0.0
    var dynamicsTiltAngle: Float = 0.4
    var dynamicsTiltBleed: Float = 0.0
    var dynamicsTiltBrightness: Float = 0.0
    var dynamicsTiltCompression: Float = 1
    var dynamicsTiltGradation: Float = 0.0
    var dynamicsTiltHue: Float = 0.0
    var dynamicsTiltOpacity: Float = 0.0
    var dynamicsTiltSaturation: Float = 0.0
    var dynamicsTiltSecondaryColor: Float = 0.0
    var dynamicsTiltShapeRoundness: Float = 1
    var dynamicsTiltShapeRoundnessMinimum: Float = 1
    var dynamicsTiltSize: Float = 0.60
    var dynamicsWetAccumulation: Float = 0.5
    var dynamicsWetnessJitter: Float = 0.0
    var eraseOpacity: Float = 1
    var eraseSize: Float = 0.33
    var extendedBlend: Int = 0
    var gradationTiltAngle: Float = 0.4
    var grainBlendMode: Int = 1
    var grainDepth: Float = 1
    var grainDepthJitter: Float = 0.0
    var grainDepthMinimum: Float = 0.0
    var grainOrientation: Int = 1
    var heightAmount: Float = 0.5
    var heightScale: Float = 0.16
    var hoverFill: Int = 2
    var hoverOutline: Int = 0
    var hoverPressure: Float = 0.4
    var hueJitterTilt: Bool = false
    var hueJitterTiltAngle: Float = 0.4
    var hueTiltAngle: Float = 0.4
    var importedFromABR: Bool = false
    var jitterSecondary: Float = 0.0
    var jitterStrokeSecondary: Float = 0.0
    var lightnessJitterTilt: Bool = false
    var lightnessJitterTiltAngle: Float = 0.4
    var maxOpacity: Float = 1
    var maxPressureSizeClamped: Bool = false
    var maxSize: Float = 7.45
    var metallicAmount: Float = 0.0
    var metallicGrainInverted: Bool = false
    var metallicScale: Float = 0.16
    var minOpacity: Float = 0.0
    var minSize: Float = 0.02
    var name: String = ""
    var opacityTiltAngle: Float = 0.4
    var oriented: Bool = false
    var paintOpacity: Float = 1
    var paintPressure: Float = 1
    var paintSize: Float = 0.06
    var pencilTaperEndLength: Float = 0.27
    var pencilTaperOpacity: Float = 1
    var pencilTaperShape: Float = 0.0
    var pencilTaperSize: Float = 0.0
    var pencilTaperSizeLinked: Bool = false
    var pencilTaperStartLength: Float = 0.18
    var pencilTipAnimation: Bool = true
    var plotFFTSmoothingAmount: Float = 0.0
    var plotFFTSmoothingBias: Float = 0.0
    var plotJitter: Float = 0.0
    var plotJitterTilt: Bool = false
    var plotJitterTiltAngle: Float = 0.4
    var plotMovingAverageStabilization: Float = 0.0
    var plotSmoothing: Float = 0.0
    var plotSpacing: Float = 0.07
    var plotSpacingVersion: Int = 1
    var previewSize: Float = 0.29
    var renderingMaxTransfer: Bool = false
    var renderingModulatedTransfer: Bool = false
    var renderingRecursiveMixing: Bool = true
    var roughnessAmount: Float = 0.5
    var roughnessGrainInverted: Bool = false
    var roughnessScale: Float = 0.16
    var saturationJitterTilt: Bool = false
    var saturationJitterTiltAngle: Float = 0.4
    var saturationTiltAngle: Float = 0.4
//    var savedEraseOpacities: String = ""
//    var savedEraseSizes: String = ""
//    var savedPaintOpacities: String = ""
//    var savedPaintSizes: String = ""
//    var savedSmudgeOpacities: String = ""
//    var savedSmudgeSizes: String = ""
    var secondaryColorJitterTilt: Bool = false
    var secondaryColorJitterTiltAngle: Float = 0.4
    var secondaryColorTiltAngle: Float = 0.4
    var shapeAngle: Float = 0.0
    var shapeAzimuth: Bool = false
    var shapeCount: Float = 0.0
    var shapeCountJitter: Float = 0.0
    var shapeCountTilt: Bool = false
    var shapeCountTiltAngle: Float = 0.4
    var shapeFilter: Bool = true
    var shapeFilterMode: Int = 0
    var shapeFlipXJitter: Bool = false
    var shapeFlipYJitter: Bool = false
    var shapeInverted: Bool = false
    var shapeOrientation: Int = 1
    var shapeRandomise: Bool = false
    var shapeRotation: Float = 0.0
    var shapeRoundness: Float = 1
    var shapeRoundnessTiltAngle: Float = 0.4
    var shapeScatter: Float = 0.15
    var sizeTiltAngle: Float = 0.4
    var smudgeOpacity: Float = 1
    var smudgeSize: Float = 0.28
    var stamp: Bool = false
    var taperEndLength: Float = 0.19
    var taperOpacity: Float = 1
    var taperPressure: Float = 0.0
    var taperShape: Float = 0.0
    var taperSize: Float = 0.0
    var taperSizeLinked: Bool = false
    var taperStartLength: Float = 0.17
    var taperVersion: Int = 1
    var textureApplication: Int = 0
    var textureBrightness: Float = 0.0
    var textureContrast: Float = 0.0
    var textureDepthTilt: Bool = false
    var textureDepthTiltAngle: Float = 0.4
    var textureFilter: Bool = false
    var textureFilterMode: Int = 0
    var textureInverted: Bool = false
    var textureMovement: Float = 1
    var textureOffsetJitter: Bool = true
    var textureOrientation: Int = 1
    var textureRotation: Float = 0.0
    var textureScale: Float = 2.36
    var textureZoom: Float = 1
    var texturizedGrainFollowsCamera: Bool = true
    var version: Int = 2
    var wetEdgesAmount: Float = 0.0

    // Implement NSCoding methods
    required convenience init?(coder decoder: NSCoder) {
        self.init()
       
        self.attackTilt = decoder.decodeBool(forKey: "attackTilt")
        self.attackTiltAngle = decoder.decodeFloat(forKey: "attackTiltAngle")
        self.authorName = decoder.decodeObject(of: NSString.self, forKey: "authorName") as? String ?? ""
        self.bleedTiltAngle = decoder.decodeFloat(forKey: "bleedTiltAngle")
        self.blendGammaCorrect = decoder.decodeBool(forKey: "blendGammaCorrect")
        self.blendMode = decoder.decodeInteger(forKey:  "blendMode")
        self.brightnessTiltAngle = decoder.decodeFloat(forKey: "brightnessTiltAngle")
        self.bundledGrainPath = decoder.decodeObject(of: NSString.self, forKey: "bundledGrainPath") as? String ?? ""
        self.bundledHeightPath = decoder.decodeObject(of: NSString.self, forKey: "bundledHeightPath") as? String ?? ""
        self.bundledMetallicPath = decoder.decodeObject(of: NSString.self, forKey: "bundledMetallicPath") as? String ?? ""
        self.bundledRoughnessPath = decoder.decodeObject(of: NSString.self, forKey: "bundledRoughnessPath") as? String ?? ""
        self.bundledShapePath = decoder.decodeObject(of: NSString.self, forKey: "bundledShapePath") as? String ?? ""
        self.burntEdgesAmount = decoder.decodeFloat(forKey: "burntEdgesAmount")
        self.burntEdgesBlendMode = decoder.decodeInteger(forKey:  "burntEdgesBlendMode")
        if let colorData = decoder.decodeObject(of: NSData.self, forKey: "color") {
            do {
                let uiColor = try NSKeyedUnarchiver.unarchivedObject(ofClass: UIColor.self, from: colorData as Data)!
                self.color = Color(uiColor: uiColor)
            } catch {
                self.color = Color(uiColor: UIColor.clear)
            }
        } else {
            self.color = Color(uiColor: UIColor.clear)
        }
        self.creationDate = decoder.decodeObject(of: NSDate.self, forKey: "creationDate") ?? NSDate()
        self.darknessJitterTilt = decoder.decodeBool(forKey: "darknessJitterTilt")
        self.darknessJitterTiltAngle = decoder.decodeFloat(forKey: "darknessJitterTiltAngle")
        self.dualBlendMode = decoder.decodeInteger(forKey:  "dualBlendMode")
        self.dynamicsBlur = decoder.decodeFloat(forKey: "dynamicsBlur")
        self.dynamicsBlurJitter = decoder.decodeFloat(forKey: "dynamicsBlurJitter")
        self.dynamicsFalloff = decoder.decodeFloat(forKey: "dynamicsFalloff")
        self.dynamicsGlazedFlow = decoder.decodeFloat(forKey: "dynamicsGlazedFlow")
        self.dynamicsJitterDarkness = decoder.decodeFloat(forKey: "dynamicsJitterDarkness")
        self.dynamicsJitterHue = decoder.decodeFloat(forKey: "dynamicsJitterHue")
        self.dynamicsJitterLightness = decoder.decodeFloat(forKey: "dynamicsJitterLightness")
        self.dynamicsJitterOpacity = decoder.decodeFloat(forKey: "dynamicsJitterOpacity")
        self.dynamicsJitterSaturation = decoder.decodeFloat(forKey: "dynamicsJitterSaturation")
        self.dynamicsJitterSize = decoder.decodeFloat(forKey: "dynamicsJitterSize")
        self.dynamicsJitterStrokeDarkness = decoder.decodeFloat(forKey: "dynamicsJitterStrokeDarkness")
        self.dynamicsJitterStrokeHue = decoder.decodeFloat(forKey: "dynamicsJitterStrokeHue")
        self.dynamicsJitterStrokeLightness = decoder.decodeFloat(forKey: "dynamicsJitterStrokeLightness")
        self.dynamicsJitterStrokeSaturation = decoder.decodeFloat(forKey: "dynamicsJitterStrokeSaturation")
        self.dynamicsLoad = decoder.decodeFloat(forKey: "dynamicsLoad")
        self.dynamicsMix = decoder.decodeFloat(forKey: "dynamicsMix")
        self.dynamicsMixSoftening = decoder.decodeFloat(forKey: "dynamicsMixSoftening")
        self.dynamicsPressureBleed = decoder.decodeFloat(forKey: "dynamicsPressureBleed")
//        self.dynamicsPressureBleedCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureBleedCurve") as? String ?? ""
        self.dynamicsPressureBleedSpeed = decoder.decodeFloat(forKey: "dynamicsPressureBleedSpeed")
        self.dynamicsPressureBrightness = decoder.decodeFloat(forKey: "dynamicsPressureBrightness")
//        self.dynamicsPressureBrightnessCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureBrightnessCurve") as? String ?? ""
        self.dynamicsPressureHue = decoder.decodeFloat(forKey: "dynamicsPressureHue")
//        self.dynamicsPressureHueCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureHueCurve") as? String ?? ""
        self.dynamicsPressureMix = decoder.decodeFloat(forKey: "dynamicsPressureMix")
        self.dynamicsPressureOpacity = decoder.decodeFloat(forKey: "dynamicsPressureOpacity")
//        self.dynamicsPressureOpacityCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureOpacityCurve") as? String ?? ""
        self.dynamicsPressureOpacitySpeed = decoder.decodeFloat(forKey: "dynamicsPressureOpacitySpeed")
        self.dynamicsPressureOpacityTransfer = decoder.decodeFloat(forKey: "dynamicsPressureOpacityTransfer")
        self.dynamicsPressureResponse = decoder.decodeFloat(forKey: "dynamicsPressureResponse")
        self.dynamicsPressureSaturation = decoder.decodeFloat(forKey: "dynamicsPressureSaturation")
//        self.dynamicsPressureSaturationCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureSaturationCurve") as? String ?? ""
        self.dynamicsPressureSecondaryColor = decoder.decodeFloat(forKey: "dynamicsPressureSecondaryColor")
//        self.dynamicsPressureSecondaryColorCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureSecondaryColorCurve") as? String ?? ""
        self.dynamicsPressureShapeRoundness = decoder.decodeFloat(forKey: "dynamicsPressureShapeRoundness")
//        self.dynamicsPressureShapeRoundnessCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureShapeRoundnessCurve") as? String ?? ""
        self.dynamicsPressureShapeRoundnessMinimum = decoder.decodeFloat(forKey: "dynamicsPressureShapeRoundnessMinimum")
        self.dynamicsPressureSize = decoder.decodeFloat(forKey: "dynamicsPressureSize")
//        self.dynamicsPressureSizeCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureSizeCurve") as? String ?? ""
        self.dynamicsPressureSizeSpeed = decoder.decodeFloat(forKey: "dynamicsPressureSizeSpeed")
        self.dynamicsPressureSmoothing = decoder.decodeFloat(forKey: "dynamicsPressureSmoothing")
//        self.dynamicsPressureTransferModulationCurve = decoder.decodeObject(of: NSString.self, forKey: "dynamicsPressureTransferModulationCurve") as? String ?? ""
        self.dynamicsSmudgeAccumulation = decoder.decodeFloat(forKey: "dynamicsSmudgeAccumulation")
        self.dynamicsSpeedOpacity = decoder.decodeFloat(forKey: "dynamicsSpeedOpacity")
        self.dynamicsSpeedSize = decoder.decodeFloat(forKey: "dynamicsSpeedSize")
        self.dynamicsTiltAngle = decoder.decodeFloat(forKey: "dynamicsTiltAngle")
        self.dynamicsTiltBleed = decoder.decodeFloat(forKey: "dynamicsTiltBleed")
        self.dynamicsTiltBrightness = decoder.decodeFloat(forKey: "dynamicsTiltBrightness")
        self.dynamicsTiltCompression = decoder.decodeFloat(forKey: "dynamicsTiltCompression")
        self.dynamicsTiltGradation = decoder.decodeFloat(forKey: "dynamicsTiltGradation")
        self.dynamicsTiltHue = decoder.decodeFloat(forKey: "dynamicsTiltHue")
        self.dynamicsTiltOpacity = decoder.decodeFloat(forKey: "dynamicsTiltOpacity")
        self.dynamicsTiltSaturation = decoder.decodeFloat(forKey: "dynamicsTiltSaturation")
        self.dynamicsTiltSecondaryColor = decoder.decodeFloat(forKey: "dynamicsTiltSecondaryColor")
        self.dynamicsTiltShapeRoundness = decoder.decodeFloat(forKey: "dynamicsTiltShapeRoundness")
        self.dynamicsTiltShapeRoundnessMinimum = decoder.decodeFloat(forKey: "dynamicsTiltShapeRoundnessMinimum")
        self.dynamicsTiltSize = decoder.decodeFloat(forKey: "dynamicsTiltSize")
        self.dynamicsWetAccumulation = decoder.decodeFloat(forKey: "dynamicsWetAccumulation")
        self.dynamicsWetnessJitter = decoder.decodeFloat(forKey: "dynamicsWetnessJitter")
        self.eraseOpacity = decoder.decodeFloat(forKey: "eraseOpacity")
        self.eraseSize = decoder.decodeFloat(forKey: "eraseSize")
        self.extendedBlend = decoder.decodeInteger(forKey:  "extendedBlend")
        self.gradationTiltAngle = decoder.decodeFloat(forKey: "gradationTiltAngle")
        self.grainBlendMode = decoder.decodeInteger(forKey:  "grainBlendMode")
        self.grainDepth = decoder.decodeFloat(forKey: "grainDepth")
        self.grainDepthJitter = decoder.decodeFloat(forKey: "grainDepthJitter")
        self.grainDepthMinimum = decoder.decodeFloat(forKey: "grainDepthMinimum")
        self.grainOrientation = decoder.decodeInteger(forKey:  "grainOrientation")
        self.heightAmount = decoder.decodeFloat(forKey: "heightAmount")
        self.heightScale = decoder.decodeFloat(forKey: "heightScale")
        self.hoverFill = decoder.decodeInteger(forKey:  "hoverFill")
        self.hoverOutline = decoder.decodeInteger(forKey:  "hoverOutline")
        self.hoverPressure = decoder.decodeFloat(forKey: "hoverPressure")
        self.hueJitterTilt = decoder.decodeBool(forKey: "hueJitterTilt")
        self.hueJitterTiltAngle = decoder.decodeFloat(forKey: "hueJitterTiltAngle")
        self.hueTiltAngle = decoder.decodeFloat(forKey: "hueTiltAngle")
        self.importedFromABR = decoder.decodeBool(forKey: "importedFromABR")
        self.jitterSecondary = decoder.decodeFloat(forKey: "jitterSecondary")
        self.jitterStrokeSecondary = decoder.decodeFloat(forKey: "jitterStrokeSecondary")
        self.lightnessJitterTilt = decoder.decodeBool(forKey: "lightnessJitterTilt")
        self.lightnessJitterTiltAngle = decoder.decodeFloat(forKey: "lightnessJitterTiltAngle")
        self.maxOpacity = decoder.decodeFloat(forKey: "maxOpacity")
        self.maxPressureSizeClamped = decoder.decodeBool(forKey: "maxPressureSizeClamped")
        self.maxSize = decoder.decodeFloat(forKey: "maxSize")
        self.metallicAmount = decoder.decodeFloat(forKey: "metallicAmount")
        self.metallicGrainInverted = decoder.decodeBool(forKey: "metallicGrainInverted")
        self.metallicScale = decoder.decodeFloat(forKey: "metallicScale")
        self.minOpacity = decoder.decodeFloat(forKey: "minOpacity")
        self.minSize = decoder.decodeFloat(forKey: "minSize")
        self.name = decoder.decodeObject(of: NSString.self, forKey: "name") as? String ?? ""
        self.opacityTiltAngle = decoder.decodeFloat(forKey: "opacityTiltAngle")
        self.oriented = decoder.decodeBool(forKey: "oriented")
        self.paintOpacity = decoder.decodeFloat(forKey: "paintOpacity")
        self.paintPressure = decoder.decodeFloat(forKey: "paintPressure")
        self.paintSize = decoder.decodeFloat(forKey: "paintSize")
        self.pencilTaperEndLength = decoder.decodeFloat(forKey: "pencilTaperEndLength")
        self.pencilTaperOpacity = decoder.decodeFloat(forKey: "pencilTaperOpacity")
        self.pencilTaperShape = decoder.decodeFloat(forKey: "pencilTaperShape")
        self.pencilTaperSize = decoder.decodeFloat(forKey: "pencilTaperSize")
        self.pencilTaperSizeLinked = decoder.decodeBool(forKey: "pencilTaperSizeLinked")
        self.pencilTaperStartLength = decoder.decodeFloat(forKey: "pencilTaperStartLength")
        self.pencilTipAnimation = decoder.decodeBool(forKey: "pencilTipAnimation")
        self.plotFFTSmoothingAmount = decoder.decodeFloat(forKey: "plotFFTSmoothingAmount")
        self.plotFFTSmoothingBias = decoder.decodeFloat(forKey: "plotFFTSmoothingBias")
        self.plotJitter = decoder.decodeFloat(forKey: "plotJitter")
        self.plotJitterTilt = decoder.decodeBool(forKey: "plotJitterTilt")
        self.plotJitterTiltAngle = decoder.decodeFloat(forKey: "plotJitterTiltAngle")
        self.plotMovingAverageStabilization = decoder.decodeFloat(forKey: "plotMovingAverageStabilization")
        self.plotSmoothing = decoder.decodeFloat(forKey: "plotSmoothing")
        self.plotSpacing = decoder.decodeFloat(forKey: "plotSpacing")
        self.plotSpacingVersion = decoder.decodeInteger(forKey:  "plotSpacingVersion")
        self.previewSize = decoder.decodeFloat(forKey: "previewSize")
        self.renderingMaxTransfer = decoder.decodeBool(forKey: "renderingMaxTransfer")
        self.renderingModulatedTransfer = decoder.decodeBool(forKey: "renderingModulatedTransfer")
        self.renderingRecursiveMixing = decoder.decodeBool(forKey: "renderingRecursiveMixing")
        self.roughnessAmount = decoder.decodeFloat(forKey: "roughnessAmount")
        self.roughnessGrainInverted = decoder.decodeBool(forKey: "roughnessGrainInverted")
        self.roughnessScale = decoder.decodeFloat(forKey: "roughnessScale")
        self.saturationJitterTilt = decoder.decodeBool(forKey: "saturationJitterTilt")
        self.saturationJitterTiltAngle = decoder.decodeFloat(forKey: "saturationJitterTiltAngle")
        self.saturationTiltAngle = decoder.decodeFloat(forKey: "saturationTiltAngle")
//        self.savedEraseOpacities = decoder.decodeObject(of: NSString.self, forKey: "savedEraseOpacities") as? String ?? ""
//        self.savedEraseSizes = decoder.decodeObject(of: NSString.self, forKey: "savedEraseSizes") as? String ?? ""
//        self.savedPaintOpacities = decoder.decodeObject(of: NSString.self, forKey: "savedPaintOpacities") as? String ?? ""
//        self.savedPaintSizes = decoder.decodeObject(of: NSString.self, forKey: "savedPaintSizes") as? String ?? ""
//        self.savedSmudgeOpacities = decoder.decodeObject(of: NSString.self, forKey: "savedSmudgeOpacities") as? String ?? ""
//        self.savedSmudgeSizes = decoder.decodeObject(of: NSString.self, forKey: "savedSmudgeSizes") as? String ?? ""
        self.secondaryColorJitterTilt = decoder.decodeBool(forKey: "secondaryColorJitterTilt")
        self.secondaryColorJitterTiltAngle = decoder.decodeFloat(forKey: "secondaryColorJitterTiltAngle")
        self.secondaryColorTiltAngle = decoder.decodeFloat(forKey: "secondaryColorTiltAngle")
        self.shapeAngle = decoder.decodeFloat(forKey: "shapeAngle")
        self.shapeAzimuth = decoder.decodeBool(forKey: "shapeAzimuth")
        self.shapeCount = decoder.decodeFloat(forKey: "shapeCount")
        self.shapeCountJitter = decoder.decodeFloat(forKey: "shapeCountJitter")
        self.shapeCountTilt = decoder.decodeBool(forKey: "shapeCountTilt")
        self.shapeCountTiltAngle = decoder.decodeFloat(forKey: "shapeCountTiltAngle")
        self.shapeFilter = decoder.decodeBool(forKey: "shapeFilter")
        self.shapeFilterMode = decoder.decodeInteger(forKey:  "shapeFilterMode")
        self.shapeFlipXJitter = decoder.decodeBool(forKey: "shapeFlipXJitter")
        self.shapeFlipYJitter = decoder.decodeBool(forKey: "shapeFlipYJitter")
        self.shapeInverted = decoder.decodeBool(forKey: "shapeInverted")
        self.shapeOrientation = decoder.decodeInteger(forKey:  "shapeOrientation")
        self.shapeRandomise = decoder.decodeBool(forKey: "shapeRandomise")
        self.shapeRotation = decoder.decodeFloat(forKey: "shapeRotation")
        self.shapeRoundness = decoder.decodeFloat(forKey: "shapeRoundness")
        self.shapeRoundnessTiltAngle = decoder.decodeFloat(forKey: "shapeRoundnessTiltAngle")
        self.shapeScatter = decoder.decodeFloat(forKey: "shapeScatter")
        self.sizeTiltAngle = decoder.decodeFloat(forKey: "sizeTiltAngle")
        self.smudgeOpacity = decoder.decodeFloat(forKey: "smudgeOpacity")
        self.smudgeSize = decoder.decodeFloat(forKey: "smudgeSize")
        self.stamp = decoder.decodeBool(forKey: "stamp")
        self.taperEndLength = decoder.decodeFloat(forKey: "taperEndLength")
        self.taperOpacity = decoder.decodeFloat(forKey: "taperOpacity")
        self.taperPressure = decoder.decodeFloat(forKey: "taperPressure")
        self.taperShape = decoder.decodeFloat(forKey: "taperShape")
        self.taperSize = decoder.decodeFloat(forKey: "taperSize")
        self.taperSizeLinked = decoder.decodeBool(forKey: "taperSizeLinked")
        self.taperStartLength = decoder.decodeFloat(forKey: "taperStartLength")
        self.taperVersion = decoder.decodeInteger(forKey:  "taperVersion")
        self.textureApplication = decoder.decodeInteger(forKey:  "textureApplication")
        self.textureBrightness = decoder.decodeFloat(forKey: "textureBrightness")
        self.textureContrast = decoder.decodeFloat(forKey: "textureContrast")
        self.textureDepthTilt = decoder.decodeBool(forKey: "textureDepthTilt")
        self.textureDepthTiltAngle = decoder.decodeFloat(forKey: "textureDepthTiltAngle")
        self.textureFilter = decoder.decodeBool(forKey: "textureFilter")
        self.textureFilterMode = decoder.decodeInteger(forKey:  "textureFilterMode")
        self.textureInverted = decoder.decodeBool(forKey: "textureInverted")
        self.textureMovement = decoder.decodeFloat(forKey: "textureMovement")
        self.textureOffsetJitter = decoder.decodeBool(forKey: "textureOffsetJitter")
        self.textureOrientation = decoder.decodeInteger(forKey:  "textureOrientation")
        self.textureRotation = decoder.decodeFloat(forKey: "textureRotation")
        self.textureScale = decoder.decodeFloat(forKey: "textureScale")
        self.textureZoom = decoder.decodeFloat(forKey: "textureZoom")
        self.texturizedGrainFollowsCamera = decoder.decodeBool(forKey: "texturizedGrainFollowsCamera")
        self.version = decoder.decodeInteger(forKey:  "version")
        self.wetEdgesAmount = decoder.decodeFloat(forKey: "wetEdgesAmount")


    }

    func encode(with aCoder: NSCoder) {

    }
}
